### ISSUE TITLE
[BUG] Error: Failed to install msedge

### ISSUE THREAD

**Issue by emakhachek** [microsoft/playwright#10695]
**Context:**
- Playwright Version: ^1.17.1
- Operating System: Linux
- Node.js version: v16.13.1
- Browser: Edge
- Extra: docker container based on official PW image

**Code Snippet**

```Dockerfile
FROM mcr.microsoft.com/playwright:bionic
RUN mkdir e2e
WORKDIR /e2e
COPY . .
RUN npm ci
```

Build container:
```
docker build -t ffui/e2e .
docker run -e USER_EMAIL -e USER_PASSWORD -it --rm --ipc=host ffui/e2e
```
Run inside container:
```
npx playwright install msedge
```
**Describe the bug**

Edge is not installed.

```
root@b4774535b186:/e2e# npx playwright install msedge
++ arch
+ [[ x86_64 == \a\a\r\c\h\6\4 ]]
+ is_user_root
+ '[' 0 -eq 0 ']'
+ maybesudo=
+ dpkg --get-selections
+ grep -q '^microsoft-edge-stable[[:space:]]*install$'
+ command -v curl
+ curl https://packages.microsoft.com/keys/microsoft.asc
+ gpg --dearmor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   1201      0 --:--:-- --:--:-- --:--:--  1200
+ install -o root -g root -m 644 /tmp/microsoft.gpg /etc/apt/trusted.gpg.d/
+ sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
+ rm /tmp/microsoft.gpg
+ apt-get update
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                                
Get:3 https://packages.microsoft.com/repos/edge stable InRelease [6817 B]                                                                                  
Err:3 https://packages.microsoft.com/repos/edge stable InRelease                                                                                        
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                                               
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                                     
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]                                                                     
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]                                
Get:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.8 kB]         
Get:9 https://deb.nodesource.com/node_16.x bionic InRelease [4584 B]                   
Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2459 kB]             
Get:11 https://deb.nodesource.com/node_16.x bionic/main amd64 Packages [770 B]             
Get:12 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [689 kB]
Get:13 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1444 kB] 
Get:14 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]                                                                                                       
Get:15 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]                                                                                                        
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2225 kB]                                                                                                 
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [34.4 kB]                                                                                               
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [725 kB]                                                                                                
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2898 kB]                                                                                                     
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]                                                                                               
Get:21 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]                                                                                                   
Reading package lists... Done                                                                                                                                                            
E: Failed to fetch https://packages.microsoft.com/repos/edge/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/repos/edge stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
+ microsoft-edge-stable --version
/e2e/node_modules/playwright/node_modules/playwright-core/bin/reinstall_msedge_stable_linux.sh: line 32: microsoft-edge-stable: command not found
Failed to install browsers
Error: Failed to install msedge
```

**Comment by yermulnik** [comment]
This a known though not yet fixed issue: https://techcommunity.microsoft.com/t5/discussions/the-edge-for-linux-deb-repository-is-not-working-today/m-p/3029703/thread-id/51108

**Comment by mxschmitt** [comment]
@emakhachek @yermulnik it should be fixed now, see [here](https://techcommunity.microsoft.com/t5/discussions/the-edge-for-linux-deb-repository-is-not-working-today/m-p/3030159/highlight/true#M51123).

**Comment by emakhachek** [comment]
Not yet for me:
````
root@2aefdec5e618:/e2e# npx playwright install msedge
++ arch
+ [[ x86_64 == \a\a\r\c\h\6\4 ]]
+ is_user_root
+ '[' 0 -eq 0 ']'
+ maybesudo=
+ dpkg --get-selections
+ grep -q '^microsoft-edge-stable[[:space:]]*install$'
+ command -v curl
+ gpg --dearmor
+ curl https://packages.microsoft.com/keys/microsoft.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   3160      0 --:--:-- --:--:-- --:--:--  3160
+ install -o root -g root -m 644 /tmp/microsoft.gpg /etc/apt/trusted.gpg.d/
+ sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
+ rm /tmp/microsoft.gpg
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 https://deb.nodesource.com/node_16.x bionic InRelease                                                              
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                         
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                 
Get:5 https://packages.microsoft.com/repos/edge stable InRelease [7342 B]                                           
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                         
Reading package lists... Done                                 
E: Release file for https://packages.microsoft.com/repos/edge/dists/stable/InRelease is not valid yet (invalid for another 5h 41min 59s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 7h 30min 9s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 7h 31min 8s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 7h 32min 18s). Updates for this repository will not be applied.
+ microsoft-edge-stable --version
/e2e/node_modules/playwright/node_modules/playwright-core/bin/reinstall_msedge_stable_linux.sh: line 32: microsoft-edge-stable: command not found
Failed to install browsers
Error: Failed to install msedge
````

Should I close this issue since it's not a Playwright problem?

**Comment by mxschmitt** [comment]
Please try again, I checked again on our CI pipelines, there it seems working.

**Comment by emakhachek** [comment]
Working.
Thanks.

**Comment by amrsa1** [comment]
@mxschmitt 

im still facing the same issue 
however im running  apt update command


```
FROM mcr.microsoft.com/playwright
COPY . /ww-PW 
RUN chmod a+x ./ww-PW/execute_test.sh
RUN apt update && apt install -y zip
RUN npm install -g allure-commandline --unsafe-perm=true --allow-root
RUN cd MPRE-PW && npm ci
RUN npx playwright install msedge
CMD [ "/bin/bash" ]
```

<img width="718" alt="Screenshot 2022-04-25 at 10 58 13" src="https://user-images.githubusercontent.com/32042806/165056030-0d2dc23f-ce26-41fe-b010-babc6c687ab6.png">

**Comment by mxschmitt** [comment]
This is a different issue, please file it separately. Microsoft Edge for Linux is not available for arm64 yet, see here:

https://techcommunity.microsoft.com/t5/discussions/edge-for-linux-arm64/m-p/1532272
