### ISSUE TITLE
[BUG] M1 visual regression bug, navigation failed because page crashed

### ISSUE THREAD

**Issue by PascalvdHoek** [microsoft/playwright#15035]
**Describe the bug**

This is the third time I submit this issue,  All closed and solved, but I still get the error. 
Hasn't solved it for me. Are there any updates when It will be solved? 

https://github.com/microsoft/playwright/issues/13722
https://github.com/microsoft/playwright/issues/13871 
merged into 
https://github.com/microsoft/playwright/issues/14236

Repros:
- https://github.com/PascalvdHoek/angular-playwright-bug

**Comment by mxschmitt** [comment]
The first was closed because we didn't get any repro. For the second it was merged into the third, not sure if it's the same tho. And the third was fixed recently (ssl not working on webkit, linux, arm).

Could you try using the development build? `npm i @playwright/test@next` to see if your issue is still persistent with the changes which get included in 1.23.

Can you confirm that you still have the same issue as in https://github.com/microsoft/playwright/issues/13871 with the same kind of project? Then I'd reopen https://github.com/microsoft/playwright/issues/13871 instead.

**Comment by PascalvdHoek** [comment]
Is there also a docker image available with this version?

**Comment by PascalvdHoek** [comment]
Still got the issue with the v1.24.0-alpha-jul-5-2022

<img width="500" alt="image" src="https://user-images.githubusercontent.com/56636556/177340883-7d02609b-b5bf-486d-bb8b-5b073638fef1.png">

**Comment by thebspin** [comment]
I still have this issue running `1.25.2` in my package and docker container

**Comment by PascalvdHoek** [comment]
@aslushnikov @dgozman @mxschmitt Any updates on this issue? or any tracks on where maybe the issue occurs? So I can do some research myself as well. But dunno where to start

**Comment by mxschmitt** [comment]
We already invested a few hours into debugging this issue. So here are some general debugging tips and direction where we should go:
- Create a more minimal example, try to understand what's required that the page crashes
- Set the `DEBUG=pw:browser,pw:protocol` env var to see what the protocol gives us, most likely just `crashed: true`
- If we have a minimal repro, we can try to use a debug build of chromium (channel: chromium-tip-of-tree) to see if a helpful stack gets printed, otherwise we should file it on crbug.com

I unfortunately don't have a m1, so i can't look into it since its m1 specific. So as of today we are pretty confident that its a Chromium bug.

**Comment by rickvandermey** [comment]
It seems like there is some progression, since 1.27.1 some of test are passing, others are failing. When looking specific at which test succeeds and which fails, the webkit version is not stable.

All chromium related test are successful 

some of the desktop-webkit fails, and most of the iphone-11-webkit fails

```
{
	name: 'desktop-webkit',
	use: { ...devices['Desktop Safari'], deviceScaleFactor: 1 },
},
{
	name: 'iphone-11-webkit',
	use: { ...devices['iPhone 11'] },
},
```

still using version 1.19.0 whereas here all tests are successful

**Comment by mxschmitt** [comment]
I can verify that this will be fixed in 1.29. You can wait until tomorrow and consume it via the canary releases: https://playwright.dev/docs/canary-releases
