### ISSUE TITLE
Looks like Playwright was just installed or updated.       ║ ║ Please run the following command to download new browsers:[BUG]

### ISSUE THREAD

**Issue by SmNizamani** [microsoft/playwright#17930]
I am getting this error while running my first playwright test in Visual studio. Here is the full message in test detail summary:
 Test1
   Source: UnitTest1.cs line 13
   Duration: 817 ms

  Message: 
Microsoft.Playwright.PlaywrightException : Executable doesn't exist at C:\Users\Nizamani\AppData\Local\ms-playwright\chromium-1024\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     pwsh bin/Debug/netX/playwright.ps1 install             ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

  Stack Trace: 
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) line 163
Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) line 61
Tests.Test1() line 18
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

**Code Snippet**
public async Task Test1()
        {
            //initialize playwright
            using var playwright = await Playwright.CreateAsync();
            //browser=
            await using var browser = await playwright.Chromium.LaunchAsync();
            //page
            var page = await browser.NewPageAsync();
            await page.GotoAsync(url:"www.google.com");
            await page.ClickAsync(selector: "text=Google Search");

**Comment by mxschmitt** [comment]
You need to open a Terminal, and then execute

`pwsh bin/Debug/net6.0/playwright.ps1 install`

inside you project's directory.

**Comment by acampa** [comment]
> You need to open a Terminal, and then execute
> 
> `pwsh bin/Debug/net6.0/playwright.ps1 install`
> 
> inside you project's directory.

I get this error message when I do:

PS C:\Users\....\Desktop\Playwright\PlayWrightDemo> pwsh bin/Debug/net6.0/playwright.ps1 install
pwsh : The term 'pwsh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pwsh bin/Debug/net6.0/playwright.ps1 install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pwsh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Using visual studio pro if that matters

**Comment by mxschmitt** [comment]
You need to install PowerShell 7+, see here: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.2

**Comment by acampa** [comment]
> You need to install PowerShell 7+, see here: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.2

Worked for me. Thank you

**Comment by ZoOoM663** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/115731329/220262775-50223053-52db-4bbe-a378-fa324c0e2984.png)
![Screenshot (8)](https://user-images.githubusercontent.com/115731329/220262785-98e6d961-10b0-44e1-822f-8bb0f05a9526.png)


can you help me?

**Comment by EdwinArroyoM** [comment]
PS TestUserGit> pwsh bin/Debug/netX/playwright.ps1 install
The argument 'bin/Debug/netX/playwright.ps1' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
                  [-ConfigurationName <string>] [-ConfigurationFile <filePath>]
                  [-CustomPipeName <string>] [-EncodedCommand <Base64EncodedCommand>]
                  [-ExecutionPolicy <ExecutionPolicy>] [-InputFormat {Text | XML}]
                  [-Interactive] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
                  [-NoProfileLoadTime] [-OutputFormat {Text | XML}]
                  [-SettingsFile <filePath>] [-SSHServerMode] [-STA]
                  [-Version] [-WindowStyle <style>]
                  [-WorkingDirectory <directoryPath>]

       pwsh[.exe] -h | -Help | -? | /?

PowerShell Online Help https://aka.ms/powershell-docs

All parameters are case-insensitive.
PS C:\Users\earroyo\Documents\NextGen\TestUserGit>

**Comment by Simon1PL** [comment]
@EdwinArroyoM 
In your case the file playwright.ps1 is probably in another directory, you can search for it. You have to change "netX" to correct directory name. In my case the path was directoryWithCsprojFile\bin\Debug\net7.0\playwright.ps1.

**Comment by Mujahid-Akber-Ali** [comment]
FIrst use this to update powershell and fix issue:
1. Go to project bin and then net6.0 or next folder and then press **shift+mouse** right click and then press open in **powershell**.
2. Then run this  **dotnet tool install --global PowerShell**    This will update powershell.
3. Then run this    **pwsh playwright.ps1 install**   to update playwrighy

Hope this help : )

**Comment by RishshriMeta** [comment]
I also getting the same error, I've tried all the above suggested fixes, but still getting the same error, please help me to fix this

**Comment by Mujahid-Akber-Ali** [comment]
Kindly share screenshot of your error, I hope I can help.

**Comment by RishshriMeta** [comment]
Thanks it is fixed now :)

**Comment by Mujahid-Akber-Ali** [comment]
Glad to hear it!

**Comment by thebsv** [comment]
Hello all, I fixed this by just running `sudo playwright install` ; for some reason it needed sudo privileges

**Comment by sagarrawat091** [comment]
Hi Team i am getting this error in window can someone help me on that
![playwright](https://github.com/user-attachments/assets/12751919-cbc3-4a06-8db6-978eea855021)

**Comment by neobsv** [comment]
Please try to download the playwright browsers using npm, using the command
npx playwright install

**Comment by cg-tester** [comment]
@neobsv thank you, solved!

**Comment by neobsv** [comment]
Oh nice, welcome

**Comment by SalesBrush** [comment]
> Hello all, I fixed this by just running `sudo playwright install` ; for some reason it needed sudo privileges

Thank you so much! This one helped me on mac.

**Comment by yermolenko-d** [comment]
How can I resolve it on prod? When I deployed it to server, like Azure app for example, or for Docker Container?

**Comment by zerobsv** [comment]
> How can I resolve it on prod? When I deployed it to server, like Azure app for example, or for Docker Container?

Hey so you should rebuild the container using a multi stage build,

For example,

FROM ubuntu as builder
...
...
RUN sudo playwright install
...
...

FROM scratch

COPY --from=builder /app /app

And then it might work, this is because the internal simulated browsers require root permissions and when you use sudo in the builder container the permissions hopefully change and then it propagates to your running container in Azure

Hope this works!

**Comment by zerobsv** [comment]
> How can I resolve it on prod? When I deployed it to server, like Azure app for example, or for Docker Container?

And yes, this is a solution for running it as the root user, you need to give it root permissions because it is playwright that is starting the browser, not the current running user

If it works with sudo, and it runs, that's the first step because I'm usually biased towards execution first over security or anything else

And if it does, then you can later install it without sudo locally first and inspect the running process 

ps -ef | grep playwright or edge or Firefox and see the user id with which the browser is getting started 

Then use chown -R <userid> /path/to/npmlibs in the container build step and then see if it works after that

Hope this helps!

**Comment by mehboob14** [comment]
getting the same issue with flask app.

**Comment by Vitalisouma** [comment]
Hello guys!  So what's the one working answer (solution) to this problem?  I am getting it right now and I have a deadline today to submit a working workflow! Am getting stuck at this same place. I have already updated Powershell and run command "pwsh bin/Debug/net10.0/playwright.ps1 install" successfully several times but still getting this error...... Heeelp!
