### ISSUE TITLE
[BUG] performance degradation since 1.29 version

### ISSUE THREAD

**Issue by Mshumaman** [microsoft/playwright#21139]
**Context:**
- Playwright Version: 1.31
- Operating System: [Windows on Gitlab CI]
- Node.js version: [18.14.2]
- Browser: [Chrome]
- Extra: [any specific details about your environment]

Since version 1.29 the duration of the tests increased (twice or more). I noticed this issue was raised before (https://github.com/microsoft/playwright/issues/19946). I've tested it on 1.30 and 1.31 and still seems that the same tests runtime duration increased substantially 

as you can see in the screenshots below Test that took 43.3 seconds in 1.27 takes 1.4 minutes in 1.31. This degradation of performance happened on all version that I checked since 1.29

Screenshot of v1.27.1
![image](https://user-images.githubusercontent.com/69470134/220851160-78aada8d-78d6-46af-8a85-6ebcc1a2f632.png)

Screenshot of 1.31
![image](https://user-images.githubusercontent.com/69470134/220851634-8fef08ff-dc2c-4360-9f5e-f1a3b4c3f07d.png)

Is it a known issue? There is new configuration since 1.29 that may effect this degradation ?

**Comment by yury-s** [comment]
> I noticed this issue was raised before (https://github.com/microsoft/playwright/issues/19946). I've tested it on 1.30 and 1.31 and still seems that the same tests runtime duration increased substantially

That issue was a Chromium bug and as mentioned in the thread it was fixed upstream, so 1.30 should contain the fix.

Did local runs also regress  or only CI? We need a reproducible example that we could run locally to debug this, any chance you can prepare one based on your test suite?

**Comment by yury-s** [comment]
Do your tests use WebGL? There were some upstream changes that could cause regressions in webgl code, we addressed that on macos but it might be that Windows requires special care.

**Comment by Mshumaman** [comment]
I've checked and our app use [mapbox.gl](http://mapbox.gl/) in some of the screens. According to Mapbox documentation its _A JavaScript library that uses WebGL to render interactive maps from vector tiles and Mapbox styles._
So in about 10% of the tests are going through the Mapbox  but it's still not explaining why other tests are slower in 1.31.

Local run also regress and I'm trying to create a reproducible example

**Comment by Mshumaman** [comment]
I checked again and seems the speed degradation happen only Gitlab CI and not locally. I ran a different suite on a different repo and the 1.31.1 was sustainably slower (test reach to 5 minute timeout on 1.31.1 but took 2 minutes on 1.27). I'm not sure how can I provide env and tests for you guys to reproduce it. Locally the same tests run at the same pace in both version

**Comment by yury-s** [comment]
> So in about 10% of the tests are going through the Mapbox but it's still not explaining why other tests are slower in 1.31.

Yeah, it would be accountable just for the 10% of the tests.

> I checked again and seems the speed degradation happen only Gitlab CI and not locally. 

Are you running with our docker image on Gitlab CI? If so, maybe you can try downgrading the image to `mcr.microsoft.com/playwright:v1.30.0-focal` (or 1.27 if that is what you updated from) and run the tests with that image to rule out changes in the container environment (we bumped Node 16 to 18 in 1.31 release), you'll need to manually install the browsers via `npx playwright install` but the rest should just work I believe.

**Comment by Mshumaman** [comment]
I ran on mcr.microsoft.com/playwright:v1.30.0-focal and got the same results. 
![image](https://user-images.githubusercontent.com/69470134/221791007-59a662d8-baf8-4efa-b397-0f47388b91e0.png)

I've checked again and seems that we use WebGL on other parts of the product (not sure what is the percentage of the tests goes through the parts) So I guess as you said maybe you should consider addressing it on Windows:

| _Do your tests use WebGL? There were some upstream changes that could cause regressions in WebGl code, we addressed that on macos but it might be that Windows requires special care._

I tried to reproduce it with a simple test on a public site (https://www.involve.me/) and compared the time on both version 1.27.1 and 1.31.1 and on the same Gitlab configuration and env and the was no time difference. But on our product I tested it on a different environments (different URLs, DB, Gitlab, GitHub) and it is consistently 1.31.1 is slower 

Me and my teammates are trying to create an env for you guys to check (it's a bit challenging security wise)

**Comment by yury-s** [comment]
> Me and my teammates are trying to create an env for you guys to check (it's a bit challenging because of security reasons)

Since the regression is specific to your app, we'll need a repro to debug this. It may well be an upstream browser regression but we cannot tell for sure without a repro.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
