### ISSUE TITLE
[BUG] Html reporter doesn't show one of the steps.

### ISSUE THREAD

**Issue by Marcin3** [microsoft/playwright#21423]
### System info
- Playwright Version: v1.31.2
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code
- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/Marcin3/challenge

or

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";
import dotenv from "dotenv";

dotenv.config();

const config: PlaywrightTestConfig = {
  testDir: "./tests",
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 10000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 2,
  reporter: "html",

  use: {
    actionTimeout: 0,
    baseURL: process.env.BASE_URL,

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on",
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],
};

export default config;

```

**Test file (self-contained)**

```ts
test("Search wrong word", async ({ page }) => {
  const wrongWord = "sythetic";
  const mainMenuPage = new MainMenuPage(page);

  await test.step(`Given User is on page https://mostly.ai/`, async () => {
    await page.goto("");
    expect(page).toHaveURL("");
  });

  await test.step(`When User click the “Search” button`, async () => {
    await mainMenuPage.clickOnSearchButton();
  });

  await test.step(`And type “sythetic” (wrong spelling of synthetic) in search field`, async () => {
    await mainMenuPage.fillSearchFiled(wrongWord);
  });

  await test.step(`And press Enter`, async () => {
    await mainMenuPage.pressEnterButtonOnSearchFiled();
  });

  await test.step(`Then User can see following information: “Sorry, no results for: sythetic”`, async () => {
    const firstPart = `Sorry, no results for:`;
    await mainMenuPage.checkSearchResult(firstPart, wrongWord);
  });
});
```

**Steps**
- Clone the repo
- First install project using command ` npm install`
- To run tests please run from root using command `npx playwright test`
- Open report  npx playwright show-report

**Expected**

For test Search wrong word you should see step When User click the “Search” button

**Actual**
Now this step is missing 
![image](https://user-images.githubusercontent.com/10815386/223079904-9edf7ce4-5774-4a5c-96dd-ddfcf59f55d9.png)

Here is also link to playwright report https://github.com/Marcin3/challenge/tree/main/playwright-report

**Comment by mxschmitt** [comment]
You have a missing await in `expect(page).toHaveURL("");` -> `await expect(page).toHaveURL("");` which should fix it.

**Comment by Marcin3** [comment]
> You have a missing await in `expect(page).toHaveURL("");` -> `await expect(page).toHaveURL("");` which should fix it.

Thank you, now with this await I can see steps.
@pavelfeldman do you want me to close this bug or you will check it?

**Comment by mxschmitt** [comment]
We will most likely implement a best effort workaround to handle such case thats why I assigned it.

**Comment by dgozman** [comment]
We can improve step nesting by using zones.

**Comment by PaulMEdwards** [comment]
I have the problem of not all `test.step()` messages showing in the HTML Report output...

> You have a missing await in `expect(page).toHaveURL("");` -> `await expect(page).toHaveURL("");` which should fix it.

I did have this as well, yet adding `await` on all `expect()` calls throughout my entire test framework codebase did NOT resolve the problem for me.

One interesting note is that I specifically removed the `await` from all `expect()` calls previously because VSCode/TypeScript says it is unnecessary:

> 'await' has no effect on the type of this expression. ts(80007)

This seems to be due to the `Expect` type returning `MakeMatchers<void, T>` instead of `MakeMatchers<Promise<void>, T>` within `@playwright > test > types > test.d.ts`.

However, if I change that as well, the same `test.step()` messages are still missing from my HTML Report output... Even if I force a failure using something like `await expect(true).toEqual(false);` the `test.step()` message containing that assertion is still missing from the HTML Report output. This makes it a little more difficult to troubleshoot test failures.

Fortunately, it does appear that the steps missing from the HTML Report output **are** being executed based on the test outcome and the video recorded by Playwright which shows the actions.

<img width="1712" alt="Screenshot 2023-03-27 at 11 32 59 PM" src="https://user-images.githubusercontent.com/153847/228353611-919dec7d-a08b-421e-a248-4637f5fb3c82.png">
<img width="1712" alt="Screenshot 2023-03-27 at 11 34 52 PM" src="https://user-images.githubusercontent.com/153847/228353613-9eae218a-4c9e-414f-a059-e6400049fa94.png">
<img width="1712" alt="Screenshot 2023-03-27 at 11 51 01 PM" src="https://user-images.githubusercontent.com/153847/228353618-c806b20b-77e5-420a-8c57-6ee5fd6f1f72.png">
<img width="1668" alt="Screenshot 2023-03-27 at 11 51 04 PM" src="https://user-images.githubusercontent.com/153847/228353626-49128d60-d9b4-48ae-a3b9-bed58e5fd8cc.png">
