### ISSUE TITLE
[BUG] VS Code extension: `playwright.env` is not applied to config file

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#22818]
**Context:**
- Playwright Version: 1.33.0
- Operating System: macOS
- Node.js version: 16.3.0
- Visual Studio Code version: 1.77.3
- Playwright for VSCode extension version: 1.0.10
- Browser: N/A
- Extra:

**Code Snippet**

`.vscode/settings.json`:
```json
{
  "playwright.env": {
    "FOO": "bar"
  }
}

```

At the top of `playwright.config.ts`:

```ts
if (process.env.FOO === undefined) {
  throw new Error("FOO env variable is not defined");
}
```

We can see that the environment variable does not exist because the error is thrown.

It seems that `playright.env` is only applied for spec files, but I feel like it should apply to the config file as well. Failing that, it would be helpful to document this behaviour.

**Comment by mxschmitt** [comment]
I can reproduce that this is broken on the current VSCode extension release but confirm that its gonna be fixed with the next vscode extension release.

**Comment by mxschmitt** [comment]
Should be fixed with VSCode extension [v1.0.11](https://github.com/microsoft/playwright-vscode/releases/tag/v1.0.11).

**Comment by irvingsoto** [comment]
how can add an entire .env file to playwright.env ?

**Comment by arojasjg** [comment]
how can add an entire .env file to playwright.env ?

**Comment by mxschmitt** [comment]
> how can add an entire .env file to playwright.env ?

@arojasjg https://playwright.dev/docs/test-parameterize#env-files

**Comment by zhkostadinov** [comment]
Hello, team. With version: 
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-117-generic snap

The issue with env vars still exists. 
The plugin is "env-cmd": "^10.1.0".  Could not resolve any var. "dotenv" is working on VSCode, but it is not on CLI.
Any idea how I can modify the plugin settings to pick up the env vars correctly?
Thanks
