### ISSUE TITLE
Regression: Debugging in Playwright Test for VSCode does not work anymore

### ISSUE THREAD

**Issue by kora-rider** [microsoft/playwright#30743]
### Version

Since 1.43.0 and also in 1.44.0

### Steps to reproduce

Precondition: clone repo https://github.com/kora-rider/Playwright_testing

1. Put the breakpoint in VSCode to any row in the test file with the name "TC001_úspěšné_přihlášení.spec.ts"
2. Run debug 

note: In case there is no breakpoint it runs well

### Expected behavior

Run the browser and stop the test on a certain breakpoint.

### Actual behavior

The browser does not run and the VSCode plugin gets stuck, even not possible to stop the debugging. 

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 61.38 MB / 16.00 GB
  Binaries:
    Node: 21.0.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ~1.44.0 => 1.44.0
```

**Comment by bhushantbn** [comment]
I have also faced same problem on vs-code extension in Ubuntu 22.04.4 LTS

**Comment by mxschmitt** [comment]
Bisected to:

- https://github.com/microsoft/playwright/compare/b41b8026627445c06bafe4ca2608a43c57c11293...da2b099b5c505b280aff338ff23dbea25dbd5e94
- 1.43.0-alpha-2024-03-20 bad
- 1.43.0-alpha-2024-03-19 good

**Comment by kora-rider** [comment]
@mxschmitt I tried VSCode insiders, but the behaviour is the same as the VSCode. I tried a plugin Playwright Test for VSCode
v1.1.1.

**Comment by mxschmitt** [comment]
@kora-rider which VSCode insiders version are you using?

**Comment by kora-rider** [comment]
@mxschmitt The last one:

Version: 1.90.0-insider (Universal)
Commit: bbc4ba1eff648ee542972589216f211b7a6a08f2
Date: 2024-05-14T05:49:42.658Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0

**Comment by kora-rider** [comment]
@mxschmitt I tried to install Node 20.X LTS, but it does not help. It only works when I downgrade Playwright to version 1.42. This configuration works for me:

System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 37.98 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - /opt/homebrew/bin/node
    npm: 10.5.2 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ~1.42.0 => 1.42.1

**Comment by iedgeleybistech** [comment]
The v1.1.1 release of the VSCode Playwright Extension seems to be the culprit. Rolling back to the previous version brings back debugging. 

![image](https://github.com/microsoft/playwright/assets/98952843/30362170-3292-41c8-9ecc-15040296e17b)

**Comment by occo-lbl** [comment]
> v1.1.1では、拡張パネルからテストフォルダのいずれかをクリックすると、無限ローダーが発生し、フォルダ内の実際のテストがパネルのドロップダウンに表示されないため、個々のテストをクリックして実行/デバッグすることはできません。
> 
> 1.0.22に戻すと、問題が一時的に解決するようです。

In my case, when I stop the test from running from the extension, I end up in an infinite loader state.
To resolve this condition, I need to restart vscode.

**Comment by guido-visser** [comment]
> In my case, if I stop running tests from the vscode extension while debugging is running, I end up in an infinite loader state. To resolve this condition, I need to restart vscode.

Experiencing the same issue here. Ctrl + P -> Reload Window is a workaround, but it's very annoying.

**Comment by occo-lbl** [comment]
Bak seems to have been resolved 6 hours ago!
Please check it out!

https://github.com/microsoft/playwright-vscode/releases/tag/v1.1.2

**Comment by kora-rider** [comment]
> Bak seems to have been resolved 6 hours ago! Please check it out!
> 
> https://github.com/microsoft/playwright-vscode/releases/tag/v1.1.2

With this version it works for me, thank you for the fix! @mxschmitt

**Comment by mxschmitt** [comment]
@kora-rider could you try v1.1.3?

**Comment by kora-rider** [comment]
@mxschmitt I tried, but it's still the same.

**Comment by gbmhunter** [comment]
v1.1.4 is still broken for me (debug won't work). Like above, reverting to v1.0.22 fixed the issue for now.

**Comment by aberonni** [comment]
This seems to be an issue again. The latest version (v1.1.13) does not work, whilst downgrading to v1.1.12 does.

**Comment by mxschmitt** [comment]
@aberonni can you file a new issue with reproduction steps and link to this one? We usually don't monitor closed issues.

**Comment by aberonni** [comment]
@mxschmitt done, thanks https://github.com/microsoft/playwright/issues/35008
