### ISSUE TITLE
www.playwright.dev does not exist

### ISSUE THREAD

**Issue by lbogerd** [microsoft/playwright#33362]
When you go to [www.playwright.dev](https://www.playwright.dev/) you get an error instead of the webpage or being redirected to [playwright.dev](https://playwright.dev/)

**Comment by Skn0tt** [comment]
Thanks for letting us know! We're looking into it.

**Comment by mxschmitt** [comment]
Should be fixed, please re-check.

**Comment by lbogerd** [comment]
I now get an SSL error - I'm guessing the certificate does not include the www. subdomain?

**Comment by Skn0tt** [comment]
I got the same error on first visit, because GitHub Pages served their `*.github.io` wildcard cert. It started working on a second request. From my experience working on CDNs, I assume they're probably lazily fetching either configuration or certificates, so this will eventually start working everywhere. Let's give it a few days. If problems persist, post another comment and i'll reopen.
